// GENERATED by scripts/sync-wasm.mjs -- do not edit by hand.
//
// Two version fields on purpose. The release manifest and the artifact's own
// embedded metadata do not always agree (dekaruntime/deka#279), and this package
// refuses to pick a winner: laundering the two into one number would hide
// exactly the drift that matters when the whole point is knowing which compiler
// validated a piece of code.
//
// `manifest` is what the release pipeline published for this file.
// `embedded` is what the wasm reports about itself at runtime.
// When they differ, trust `sha256` -- it identifies the bytes unambiguously.

export const bundledWasmInfo = Object.freeze({
  manifestVersion: '0.32.1',
  embeddedVersion: '0.32.1',
  releaseVersion: '0.32.1',
  sourceCommit: 'bf2b1a7993629e49bf43c429a80a6fd35368ee1d',
  sha256: '03c0b256f511d2dd3e092b509e5ebae21a1f67460e6383c41d34cf9f4db8c0a9',
  target: 'wasm32-unknown-unknown',
  abiVersion: 1,
  syncedAt: '2026-08-25',
});

/**
 * The compiler version, as reported by the artifact itself.
 *
 * Deliberately NOT the CDN sidecar or the release tag: the bytes are what the
 * compiler is, the tag is what we meant to publish. When those disagree the tag
 * is the thing that is wrong (deka#279).
 */
export const wasmVersion = bundledWasmInfo.embeddedVersion;

/** The runtime commit the artifact was built from. Unambiguous; prefer it. */
export const wasmSourceCommit = bundledWasmInfo.sourceCommit;
