// GENERATED by scripts/sync-wasm.mjs -- do not edit by hand.
//
// Two version fields on purpose. The release manifest and the artifact's own
// embedded metadata do not always agree (dekaruntime/deka#279), and this package
// refuses to pick a winner: laundering the two into one number would hide
// exactly the drift that matters when the whole point is knowing which compiler
// validated a piece of code.
//
// `manifest` is what the release pipeline published for this file.
// `embedded` is what the wasm reports about itself at runtime.
// When they differ, trust `sha256` -- it identifies the bytes unambiguously.

export const bundledWasmInfo = Object.freeze({
  manifestVersion: '0.32.0',
  embeddedVersion: '0.32.0',
  releaseVersion: '0.32.0',
  sourceCommit: 'd35e84df39115995b0c24e2994742d79d49b8c9c',
  sha256: 'ab0aa32ee8160f46c8a5945b7811be0bdc83df23c635d02af585986feece75e2',
  target: 'wasm32-unknown-unknown',
  abiVersion: 1,
  syncedAt: '2026-08-25',
});

/**
 * The compiler version, as reported by the artifact itself.
 *
 * Deliberately NOT the CDN sidecar or the release tag: the bytes are what the
 * compiler is, the tag is what we meant to publish. When those disagree the tag
 * is the thing that is wrong (deka#279).
 */
export const wasmVersion = bundledWasmInfo.embeddedVersion;

/** The runtime commit the artifact was built from. Unambiguous; prefer it. */
export const wasmSourceCommit = bundledWasmInfo.sourceCommit;
