// GENERATED by scripts/sync-wasm.mjs -- do not edit by hand.
//
// Two version fields on purpose. The release manifest and the artifact's own
// embedded metadata do not always agree (dekaruntime/deka#279), and this package
// refuses to pick a winner: laundering the two into one number would hide
// exactly the drift that matters when the whole point is knowing which compiler
// validated a piece of code.
//
// `manifest` is what the release pipeline published for this file.
// `embedded` is what the wasm reports about itself at runtime.
// When they differ, trust `sha256` -- it identifies the bytes unambiguously.

export const bundledWasmInfo = Object.freeze({
  manifestVersion: '0.34.0',
  embeddedVersion: '0.34.0',
  releaseVersion: '0.34.0',
  sourceCommit: '8bfdf31ab1cfc93ae4d939a6bf925fee901ab4f5',
  sha256: 'eba9d5748b7d55c7ed795d4bb12c1ca4043bcbc7c95bca632914ad82aa2d69b9',
  target: 'wasm32-unknown-unknown',
  abiVersion: 1,
  syncedAt: '2026-08-28',
});

/**
 * The compiler version, as reported by the artifact itself.
 *
 * Deliberately NOT the CDN sidecar or the release tag: the bytes are what the
 * compiler is, the tag is what we meant to publish. When those disagree the tag
 * is the thing that is wrong (deka#279).
 */
export const wasmVersion = bundledWasmInfo.embeddedVersion;

/** The runtime commit the artifact was built from. Unambiguous; prefer it. */
export const wasmSourceCommit = bundledWasmInfo.sourceCommit;
